package com.example.jpasql.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;


@Entity
@Table(name = "accounts")
public class Account {
    @NotNull
    @Column
    private String username;

    @NotNull
    @Column
    private String password;

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }



    // Public methods

    public Account() { }

    public Account(long id) {
        this.id = id;
    }

    public Account(String username, String password) {
        this.password=password;
        this.username=username;
    }


}
